interface FixtureDates {
  isoDay: (offset: number) => string;
  modified: (offset: number) => string;
}

const line = (itemCode: string, itemName: string, qty: number, rate: number) => ({
  item_code: itemCode,
  item_name: itemName,
  qty,
  rate,
  amount: qty * rate,
  uom: "pcs",
});

export function buildShowcaseDocs({ isoDay, modified }: FixtureDates): Record<string, unknown>[] {
  const customers = [
    ["CUST-0002", "Cedar & Co", "hello@cedarco.example", 12_600, 128_400],
    ["CUST-0003", "Atelier Nine", "studio@ateliernine.example", 0, 96_200],
    ["CUST-0004", "Meridian Labs", "ops@meridianlabs.example", 31_500, 214_800],
    ["CUST-0005", "Harbor & Pine", "orders@harborpine.example", 8_400, 74_600],
    ["CUST-0006", "Saffron Hotels", "procurement@saffronhotels.example", 42_700, 286_100],
  ].map(([name, customerName, email, outstanding, totalSales], index) => ({
    doctype: "Customer",
    name,
    customer_name: customerName,
    customer_type: "Company",
    customer_group: index > 2 ? "Enterprise" : "Commercial",
    territory: "United States",
    email_id: email,
    mobile_no: `+1 415 555 01${String(index + 2).padStart(2, "0")}`,
    default_currency: "USD",
    payment_terms: index > 2 ? "Net 30" : "Net 15",
    disabled: 0,
    outstanding_amount: outstanding,
    total_sales_amount: totalSales,
    creation: modified(-48 + index * 5),
    modified: modified(-index),
    owner: "admin@demo.amni",
  }));

  const products = [
    ["SKU-VAULT", "Vault executive desk", 1_250, 780, 5],
    ["SKU-HALO", "Halo pendant light", 390, 210, 10],
    ["SKU-MOSS", "Moss modular sofa", 1_840, 1_120, 3],
    ["SKU-FORM", "Form counter stool", 320, 170, 8],
    ["SKU-LINE", "Line shelving system", 920, 560, 4],
    ["SKU-ORBIT", "Orbit side table", 460, 270, 6],
  ].map(([code, name, standardRate, valuationRate, safetyStock]) => ({
    doctype: "Item",
    name: code,
    item_code: code,
    item_name: name,
    item_group: "Furniture",
    stock_uom: "pcs",
    standard_rate: standardRate,
    valuation_rate: valuationRate,
    safety_stock: safetyStock,
    disabled: 0,
    creation: modified(-50),
    modified: modified(-1),
  }));

  const bins = [
    ["BIN-VAULT-MAIN", "SKU-VAULT", "Main Warehouse - DC", 12, 2, 780],
    ["BIN-HALO-MAIN", "SKU-HALO", "Main Warehouse - DC", 46, 8, 210],
    ["BIN-MOSS-FULFIL", "SKU-MOSS", "Fulfilment Center - DC", 2, 1, 1_120],
    ["BIN-FORM-FULFIL", "SKU-FORM", "Fulfilment Center - DC", 28, 5, 170],
    ["BIN-LINE-MAIN", "SKU-LINE", "Main Warehouse - DC", 7, 1, 560],
    ["BIN-ORBIT-SHOW", "SKU-ORBIT", "Showroom - DC", 9, 2, 270],
    ["BIN-NIMBUS-FULFIL", "SKU-NIMBUS", "Fulfilment Center - DC", 22, 4, 420],
    ["BIN-ARC-MAIN", "SKU-ARC", "Main Warehouse - DC", 16, 3, 130],
  ].map(([name, itemCode, warehouse, actualQty, reservedQty, valuationRate]) => ({
    doctype: "Bin",
    name,
    item_code: itemCode,
    warehouse,
    actual_qty: actualQty,
    reserved_qty: reservedQty,
    projected_qty: Number(actualQty) - Number(reservedQty),
    valuation_rate: valuationRate,
  }));

  const suppliers = [
    ["SUP-0001", "Alder Materials", "Raw Materials", 14_800, 118_600],
    ["SUP-0002", "Luma Components", "Components", 0, 84_900],
    ["SUP-0003", "Northline Logistics", "Services", 6_250, 46_700],
    ["SUP-0004", "Terra Textiles", "Textiles", 21_300, 132_400],
  ].map(([name, supplierName, group, outstanding, totalPurchases], index) => ({
    doctype: "Supplier",
    name,
    supplier_name: supplierName,
    supplier_group: group,
    email_id: `accounts${index + 1}@supplier.example`,
    mobile_no: `+1 510 555 02${String(index + 1).padStart(2, "0")}`,
    default_currency: "USD",
    payment_terms: "Net 30",
    tax_id: `US-DEMO-${1000 + index}`,
    disabled: 0,
    outstanding_amount: outstanding,
    total_receipt_amount: totalPurchases,
    creation: modified(-60 + index * 7),
    modified: modified(-index),
  }));

  const quotations = [
    [
      "QTN-2026-022",
      "CUST-0004",
      -3,
      11,
      31_500,
      "Sent",
      1,
      "SKU-VAULT",
      "Vault executive desk",
      18,
      1_250,
    ],
    [
      "QTN-2026-023",
      "CUST-0006",
      -1,
      20,
      47_240,
      "Draft",
      0,
      "SKU-HALO",
      "Halo pendant light",
      64,
      390,
    ],
    [
      "QTN-2026-024",
      "CUST-0002",
      -18,
      -2,
      18_720,
      "Ordered",
      1,
      "SKU-LINE",
      "Line shelving system",
      12,
      920,
    ],
    [
      "QTN-2026-025",
      "CUST-0005",
      -42,
      -28,
      9_800,
      "Expired",
      1,
      "SKU-NIMBUS",
      "Nimbus task chair",
      10,
      680,
    ],
  ].map(
    (
      [name, customer, date, validUntil, total, status, docstatus, itemCode, itemName, qty, rate],
      index,
    ) => ({
      doctype: "Quotation",
      name,
      customer,
      transaction_date: isoDay(Number(date)),
      valid_till: isoDay(Number(validUntil)),
      currency: "USD",
      grand_total: total,
      status,
      docstatus,
      items: [line(String(itemCode), String(itemName), Number(qty), Number(rate))],
      notes: "Curated commercial proposal for the Demo Co showcase workspace.",
      owner: index % 2 === 0 ? "admin@demo.amni" : "member@demo.amni",
      creation: modified(Number(date)),
      modified: modified(Math.min(Number(date) + 2, -1)),
    }),
  );

  const salesOrders = [
    [
      "SO-2026-015",
      "CUST-0002",
      -14,
      4,
      18_720,
      "To Deliver and Bill",
      1,
      "SKU-LINE",
      "Line shelving system",
      12,
      920,
    ],
    [
      "SO-2026-016",
      "CUST-0003",
      -30,
      -8,
      27_600,
      "Delivered",
      1,
      "SKU-MOSS",
      "Moss modular sofa",
      15,
      1_840,
    ],
    [
      "SO-2026-017",
      "CUST-0004",
      -2,
      16,
      31_500,
      "To Deliver",
      1,
      "SKU-VAULT",
      "Vault executive desk",
      18,
      1_250,
    ],
    [
      "SO-2026-018",
      "CUST-0006",
      -1,
      28,
      47_240,
      "Draft",
      0,
      "SKU-HALO",
      "Halo pendant light",
      64,
      390,
    ],
  ].map(
    (
      [name, customer, date, delivery, total, status, docstatus, itemCode, itemName, qty, rate],
      index,
    ) => ({
      doctype: "Sales Order",
      name,
      customer,
      transaction_date: isoDay(Number(date)),
      delivery_date: isoDay(Number(delivery)),
      currency: "USD",
      grand_total: total,
      status,
      docstatus,
      items: [line(String(itemCode), String(itemName), Number(qty), Number(rate))],
      notes: "Showcase order with realistic fulfilment timing.",
      owner: index % 2 === 0 ? "admin@demo.amni" : "member@demo.amni",
      creation: modified(Number(date)),
      modified: modified(-1),
    }),
  );

  const salesInvoices = [
    ["SINV-2026-004", "CUST-0004", -2, 18, 31_500, 31_500, "SO-2026-017"],
    ["SINV-2026-005", "CUST-0003", -29, -12, 27_600, 0, "SO-2026-016"],
    ["SINV-2026-006", "CUST-0005", -21, -7, 16_800, 8_400, "SO-2026-014"],
    ["SINV-2026-007", "CUST-0006", -8, 22, 42_700, 42_700, "SO-2026-018"],
    ["SINV-2026-008", "CUST-0002", -1, 29, 18_720, 18_720, "SO-2026-015"],
  ].map(([name, customer, date, due, total, outstanding, salesOrder], index) => ({
    doctype: "Sales Invoice",
    name,
    customer,
    posting_date: isoDay(Number(date)),
    due_date: isoDay(Number(due)),
    currency: "USD",
    grand_total: total,
    outstanding_amount: outstanding,
    sales_order: salesOrder,
    status: Number(outstanding) === 0 ? "Paid" : Number(due) < 0 ? "Overdue" : "Unpaid",
    docstatus: 1,
    items: [line("SKU-VAULT", "Vault executive desk", 5 + index, Number(total) / (5 + index))],
    notes: "Showcase invoice generated for the Demo Co operating workspace.",
    owner: index % 2 === 0 ? "admin@demo.amni" : "member@demo.amni",
    creation: modified(Number(date)),
    modified: modified(-1),
  }));

  const payments = [
    ["PAY-2026-003", "Receive", "Customer", "CUST-0003", 27_600, -11, "BANK-8421", "SINV-2026-005"],
    ["PAY-2026-004", "Receive", "Customer", "CUST-0005", 8_400, -5, "CARD-6634", "SINV-2026-006"],
    ["PAY-2026-005", "Receive", "Customer", "CUST-0002", 40_000, -9, "BANK-9182", "SINV-2026-002"],
    ["PAY-2026-006", "Pay", "Supplier", "SUP-0001", 12_400, -4, "WIRE-2014", "PINV-2026-001"],
  ].map(([name, paymentType, partyType, party, amount, date, reference, billNo]) => ({
    doctype: "Payment Entry",
    name,
    payment_type: paymentType,
    party_type: partyType,
    party,
    paid_amount: amount,
    received_amount: amount,
    mode_of_payment: paymentType === "Receive" ? "bank_transfer" : "wire",
    posting_date: isoDay(Number(date)),
    reference_no: reference,
    bill_no: billNo,
    docstatus: 1,
    owner: "admin@demo.amni",
  }));

  const purchaseOrders = [
    ["PO-2026-001", "SUP-0001", "Alder Materials", -20, 5, 24_800, "SKU-VAULT", 20, 1_240],
    ["PO-2026-002", "SUP-0002", "Luma Components", -12, 8, 11_700, "SKU-HALO", 30, 390],
    ["PO-2026-003", "SUP-0003", "Northline Logistics", -7, 2, 6_250, "SKU-LINE", 5, 1_250],
    ["PO-2026-004", "SUP-0004", "Terra Textiles", -3, 18, 21_300, "SKU-MOSS", 15, 1_420],
  ].map(([name, supplier, supplierName, date, due, total, itemCode, qty, rate], index) => ({
    doctype: "Purchase Order",
    name,
    supplier,
    supplier_name: supplierName,
    transaction_date: isoDay(Number(date)),
    schedule_date: isoDay(Number(due)),
    currency: "USD",
    grand_total: total,
    status: index === 2 ? "Completed" : "To Receive and Bill",
    docstatus: 1,
    items: [line(String(itemCode), String(itemCode), Number(qty), Number(rate))],
    notes: "Demo purchasing order with realistic fulfilment timing.",
    owner: index % 2 === 0 ? "admin@demo.amni" : "member@demo.amni",
    creation: modified(Number(date)),
    modified: modified(-1),
  }));

  const purchaseInvoices = [
    ["PINV-2026-001", "SUP-0001", "Alder Materials", -18, -3, 24_800, 12_400, "PO-2026-001"],
    ["PINV-2026-002", "SUP-0002", "Luma Components", -10, 12, 11_700, 11_700, "PO-2026-002"],
    ["PINV-2026-003", "SUP-0003", "Northline Logistics", -6, 4, 6_250, 0, "PO-2026-003"],
    ["PINV-2026-004", "SUP-0004", "Terra Textiles", -2, 25, 21_300, 21_300, "PO-2026-004"],
  ].map(([name, supplier, supplierName, date, due, total, outstanding, purchaseOrder], index) => ({
    doctype: "Purchase Invoice",
    name,
    supplier,
    supplier_name: supplierName,
    posting_date: isoDay(Number(date)),
    due_date: isoDay(Number(due)),
    currency: "USD",
    grand_total: total,
    outstanding_amount: outstanding,
    purchase_order: purchaseOrder,
    status: Number(outstanding) === 0 ? "Paid" : Number(due) < 0 ? "Overdue" : "Unpaid",
    docstatus: 1,
    items: [
      line(
        index % 2 === 0 ? "SKU-VAULT" : "SKU-HALO",
        "Showcase inventory",
        5 + index,
        Number(total) / (5 + index),
      ),
    ],
    remarks: "Vendor invoice included in the Demo Co showcase ledger.",
    owner: "admin@demo.amni",
    creation: modified(Number(date)),
    modified: modified(-1),
  }));

  const expenses = [
    [
      "EXP-0001",
      "travel",
      -16,
      "Client workshop travel to Seattle",
      "Northline Logistics",
      1_860,
      "Approved",
      "",
    ],
    [
      "EXP-0002",
      "software",
      -11,
      "Design and collaboration software",
      "",
      920,
      "Approved",
      "PAY-2026-007",
    ],
    [
      "EXP-0003",
      "marketing",
      -7,
      "Spring collection campaign photography",
      "Atelier Nine",
      4_800,
      "Submitted",
      "",
    ],
    [
      "EXP-0004",
      "office",
      -4,
      "Showroom materials and supplies",
      "Alder Materials",
      1_240,
      "Approved",
      "PAY-2026-008",
    ],
    [
      "EXP-0005",
      "professional_services",
      -2,
      "Quarterly compliance review",
      "",
      3_600,
      "Draft",
      "",
    ],
  ].map(
    (
      [name, category, date, description, supplier, amount, approvalStatus, paymentReference],
      index,
    ) => ({
      doctype: "Expense Claim",
      name,
      expense_type: category,
      posting_date: `${isoDay(Number(date))}T09:00:00.000Z`,
      remarks: description,
      supplier: supplier || undefined,
      grand_total: amount,
      approval_status: approvalStatus,
      expense_approver: index % 2 === 0 ? "member@demo.amni" : "admin@demo.amni",
      payment_reference: paymentReference || undefined,
      docstatus: approvalStatus === "Draft" ? 0 : 1,
      creation: `${isoDay(Number(date))}T09:00:00.000Z`,
      modified: `${isoDay(-1)}T09:00:00.000Z`,
    }),
  );

  return [
    ...customers,
    ...products,
    {
      doctype: "Warehouse",
      name: "Fulfilment Center - DC",
      warehouse_name: "Fulfilment Center",
      is_group: 0,
      disabled: 0,
    },
    ...bins,
    ...suppliers,
    ...quotations,
    ...salesOrders,
    ...salesInvoices,
    ...payments,
    ...purchaseOrders,
    ...purchaseInvoices,
    ...expenses,
  ];
}
